### PR TITLE
6.x Initial Support

### PR DESCRIPTION
**Pull request by msheiny**
Not a lot of crazy changes to be added to this role for 6.x support - there are some changes notably with mapping types and kibana dashboard export though. Luckily, the kibana default dashboard import can now be handled via the configuration.

### CODE REVIEW

**Comment by conorsch** [comment]
CI is failing, will try to reproduce locally.

**Comment by ageis** [comment]
@msheiny Don't forget to remove Topbeat stuff too.

**Comment by msheiny** [comment]
> @msheiny Don't forget to remove Topbeat stuff too. 

That seems unrelated to this PR, no? I'm happy to take a PR and ticket for that issue though. I think it's kind of out-of-scope for the role (removing old legacy packages - especially without an opt-in) but if someone else wants to do the work here - I'm happy to include it :)

**Comment by msheiny** [comment]
> Default config fails during kibana dashboard import. Comments in role defaults say it won't work, and recommend manual, but let's not run it if we know it won't work.

Yeahhhh this is a good call... I was wondering how to handle this logic, looking for the import_dashboards command seems to be a good move 👍

**Comment by msheiny** [comment]
So I had to squash some of the metricbeat tests here -- i know what to do to fix them but I had to timebox myself to keep moving 🤷‍♂️ if its a blocker for merge for now let me know and i'll keep this PR open for a bit longer.

**Comment by msheiny** [comment]
@conorsch ping for re-review :)

**Comment by msheiny** [comment]
heyyyyyy @conorsch  ping here! i got another PR incoming :angel:

**Comment by msheiny** [comment]
or maybe... i take that back... ill sync with ya tomorrow :)

**Pull request merged**
